
version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "development"
    open-pull-requests-limit: 5

    labels:
      - "dependencies"
      - "yarn"


    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

 
  